useless_words = [
    "Solution", "solution",
    "Answer", "answer",
    "Response", "response",
    "Explanation", "explanation",
    "Statement", "statement",
    "Query", "query",
    "Clarification", "clarification",
    "Insight", "insight",
    "Task", "task",
    "Objective", "objective",
    "Challenge", "challenge",
    "Instruction", "instruction",
    "Process", "process",
    "Steps", "steps",
    "Guidelines", "guidelines",
    "Compute", "compute",
    "Algorithm", "algorithm",
    "Execution", "execution",
    "Function", "function",
    "Output", "output",
    "Variable", "variable",
    "Parameter", "parameter",
    "*", "#", "-", "_", ">", "\\n", "\\t",
    "{", "}", "[", "]", "(", ")",
    "=>", "::", "\"\"\"",
    "Σ", "∫", "≈", "→", "⊆",
    "#","http","https","()",
    "(",")","%",'1','2','3','4','5','6','7','8','9','0'
]
